### ISSUE TITLE
Stored XSS vulnerability in rpcms

### ISSUE THREAD

**Issue by Zer0Bs** [ralap-z/rpcms#6]
友链-添加:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/50673654/207648042-b554b469-54f4-474f-b1e1-97f8cbf717d7.png">

<img width="737" alt="image" src="https://user-images.githubusercontent.com/50673654/207648550-cfaf2ff6-baee-4839-9458-b3caff32535e.png">

**Comment by ralap-z** [comment]
Thank you very much for your feedback. The technology is being processed
