### ISSUE TITLE
RPCMS v3.6.1 XXS

### ISSUE THREAD

**Issue by n2ryx** [ralap-z/rpcms#8]

**Comment by ralap-z** [comment]
Thank you very much for providing feedback on the vulnerability. It has been fixed in the form of a plugin(https://app.rpcms.cn/app/157.html)
Thank you again

**Comment by n2ryx** [comment]
Good boy !!







| |
Night
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 4/25/2024 18:42 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [ralap-z/rpcms] RPCMS v3.6.1 XXS (Issue #8) |

Thank you very much for providing feedback on the vulnerability. It has been fixed in the form of a plugin(https://app.rpcms.cn/app/157.html)
Thank you again
